<?php

namespace Tests\Feature;

use App\Models\Category;
use App\Models\Product;
use App\Models\Supplier;
use App\Models\User;
use Database\Seeders\DatabaseSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Spatie\Permission\PermissionRegistrar;
use Tests\TestCase;

class ConsignmentWorkflowRulesTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();

        app(PermissionRegistrar::class)->forgetCachedPermissions();
        $this->seed(DatabaseSeeder::class);
    }

    public function test_product_creation_auto_generates_consignment_for_auto_supplier_types(): void
    {
        $user = $this->signInAsAdmin();
        $category = $this->createCategory();
        $supplier = $this->createSupplier('cho_tang', 'NCC cho tang');

        $response = $this->post(route('products.store'), [
            'supplier_id' => $supplier->id,
            'category_id' => $category->id,
            'name' => 'Ao len',
            'sale_price' => 150000,
            'quantity' => 2,
            'description' => 'Tu dong tao phieu',
        ]);

        $response->assertRedirect(route('products.index'));

        $product = Product::query()->with('consignmentNote')->sole();

        $this->assertNotNull($product->consignmentNote);
        $this->assertTrue($product->consignmentNote->isAutoGenerated());
        $this->assertSame($supplier->id, $product->consignmentNote->supplier_id);
        $this->assertSame($user->id, $product->consignmentNote->responsible_user_id);
        $this->assertSame(2, $product->consignmentNote->quantity);
        $this->assertNotSame('', (string) $product->consignmentNote->public_id);
    }

    public function test_product_creation_stores_uploaded_image_without_client_side_compression(): void
    {
        Storage::fake('public');

        $this->signInAsAdmin();
        $category = $this->createCategory();
        $supplier = $this->createSupplier('cho_tang', 'NCC cho tang');

        $response = $this->post(route('products.store'), [
            'supplier_id' => $supplier->id,
            'category_id' => $category->id,
            'name' => 'Ao khoac',
            'sale_price' => 250000,
            'quantity' => 1,
            'description' => 'Upload anh lon',
            'image' => UploadedFile::fake()->image('ao-khoac.jpg', 4000, 3000),
        ]);

        $response->assertRedirect(route('products.index'));

        $product = Product::query()->sole();

        $this->assertNotNull($product->image_path);
        Storage::disk('public')->assertExists($product->image_path);
    }

    public function test_manual_supplier_types_still_require_an_explicit_consignment_note(): void
    {
        $this->signInAsAdmin();
        $category = $this->createCategory();
        $supplier = $this->createSupplier('ncc_it_san_pham', 'NCC it san pham');

        $response = $this->from(route('products.index'))->post(route('products.store'), [
            'supplier_id' => $supplier->id,
            'category_id' => $category->id,
            'name' => 'Quan jean',
            'sale_price' => 220000,
            'quantity' => 1,
        ]);

        $response->assertRedirect(route('products.index'));
        $response->assertSessionHasErrors('consignment_note_id');
        $this->assertDatabaseCount('products', 0);
    }

    public function test_consignment_creation_is_rejected_for_auto_generated_supplier_types(): void
    {
        $this->signInAsAdmin();
        $supplier = $this->createSupplier('khach_si', 'Khach si');

        $response = $this->from(route('consignments.index'))->post(route('consignments.store'), [
            'responsible_name' => 'Nguoi tao',
            'supplier_id' => $supplier->id,
            'sent_date' => now()->toDateString(),
            'quantity' => 3,
            'notes' => 'Khong duoc tao thu cong',
        ]);

        $response->assertRedirect(route('consignments.index'));
        $response->assertSessionHasErrors('supplier_id');
        $this->assertDatabaseCount('consignment_notes', 0);
    }

    public function test_product_index_searches_by_product_code_supplier_code_and_product_name(): void
    {
        $this->signInAsAdmin();
        $category = $this->createCategory();
        $supplierA = $this->createSupplier('cho_tang', 'NCC A');
        $supplierB = $this->createSupplier('khach_si', 'NCC B');

        $this->post(route('products.store'), [
            'supplier_id' => $supplierA->id,
            'category_id' => $category->id,
            'name' => 'Ao so mi xanh',
            'sale_price' => 120000,
            'quantity' => 1,
            'description' => null,
        ])->assertRedirect(route('products.index'));

        $this->post(route('products.store'), [
            'supplier_id' => $supplierB->id,
            'category_id' => $category->id,
            'name' => 'Quan tay den',
            'sale_price' => 220000,
            'quantity' => 1,
            'description' => null,
        ])->assertRedirect(route('products.index'));

        $productA = Product::query()->where('name', 'Ao so mi xanh')->sole();
        $productB = Product::query()->where('name', 'Quan tay den')->sole();

        $responseByProductCode = $this->get(route('products.index', ['q' => $productA->public_id]));
        $responseByProductCode->assertOk();
        $responseByProductCode->assertSee('Ao so mi xanh');
        $responseByProductCode->assertDontSee('Quan tay den');

        $responseBySupplierCode = $this->get(route('products.index', ['q' => $supplierB->public_id]));
        $responseBySupplierCode->assertOk();
        $responseBySupplierCode->assertSee('Quan tay den');
        $responseBySupplierCode->assertDontSee('Ao so mi xanh');

        $responseByName = $this->get(route('products.index', ['q' => 'ao so mi']));
        $responseByName->assertOk();
        $responseByName->assertSee('Ao so mi xanh');
        $responseByName->assertDontSee('Quan tay den');
    }

    private function signInAsAdmin(): User
    {
        $user = User::factory()->create([
            'password' => 'password',
        ]);
        $user->assignRole('admin');

        $this->actingAs($user);

        return $user;
    }

    private function createCategory(): Category
    {
        return Category::create([
            'name' => 'Danh muc test',
            'description' => null,
            'is_active' => true,
        ]);
    }

    private function createSupplier(string $type, string $name): Supplier
    {
        return Supplier::create([
            'responsible_name' => 'Nguoi phu trach',
            'type' => $type,
            'name' => $name,
            'phone' => null,
            'bank_name' => null,
            'bank_account_name' => null,
            'bank_account_number' => null,
            'notes' => null,
        ]);
    }
}
