<x-app-layout>
    <x-slot name="header">
        <div>
            <h2 class="text-2xl font-semibold text-gray-900">Sửa sản phẩm</h2>
            <p class="text-sm text-gray-500">Cập nhật thông tin sản phẩm, giá và ảnh chụp từ thiết bị.</p>
            <p class="mt-1 text-xs font-medium uppercase tracking-wide text-gray-400">Mã công khai: #{{ $product->public_id_display }}</p>
        </div>
    </x-slot>

    @php
        $supplierOptions = $suppliers->map(fn ($supplier) => [
            'value' => $supplier->id,
            'label' => '#'.$supplier->public_id_display.' - '.$supplier->name,
        ])->all();
        $supplierTypeMap = $suppliers->mapWithKeys(fn ($supplier) => [(string) $supplier->id => $supplier->type])->all();

        $categoryOptions = $categories->map(fn ($category) => [
            'value' => $category->id,
            'label' => '#'.$category->public_id_display.' - '.$category->name,
        ])->all();
    @endphp

    <div class="py-10">
        <div class="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
            <div
                class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-gray-200"
                x-data="{
                    supplierTypes: @js($supplierTypeMap),
                    manualTypes: @js(\App\Models\Supplier::MANUAL_CONSIGNMENT_TYPES),
                    autoTypes: @js(\App\Models\Supplier::AUTO_CONSIGNMENT_TYPES),
                    selectedSupplierId: @js((string) old('supplier_id', $product->supplier_id)),
                    init() {
                        window.addEventListener('searchable-select-change', (event) => {
                            if (event.detail?.name !== 'supplier_id') {
                                return;
                            }

                            this.selectedSupplierId = String(event.detail?.value ?? '');
                        });
                    },
                    get selectedSupplierType() {
                        return this.supplierTypes[this.selectedSupplierId] ?? '';
                    },
                    get requiresManualConsignment() {
                        return this.manualTypes.includes(this.selectedSupplierType);
                    },
                    get usesAutoGeneratedConsignment() {
                        return this.autoTypes.includes(this.selectedSupplierType);
                    },
                }"
            >
                <form method="POST" action="{{ route('products.update', $product) }}" enctype="multipart/form-data" class="space-y-4">
                    @csrf
                    @method('PUT')
                    <x-image-upload-preview
                        name="image"
                        label="Ảnh sản phẩm"
                        :current-url="$product->image_path ? asset('storage/' . $product->image_path) : null"
                        helper-text="Ảnh sẽ được tối ưu tự động trên trình duyệt (resize và nén) trước khi upload. Bạn vẫn có thể chọn ảnh từ camera hoặc thư viện thiết bị."
                    />
                    @error('image') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    @php
                        $selectedSupplierId = old('supplier_id', $product->supplier_id);
                    @endphp
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Nhà cung cấp</label>
                        <x-searchable-select
                            name="supplier_id"
                            :options="$supplierOptions"
                            :selected="$selectedSupplierId"
                            placeholder="-- Chọn NCC --"
                            search-placeholder="Tìm theo mã hoặc tên"
                            empty-text="Không có nhà cung cấp phù hợp"
                        />
                        @error('supplier_id') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    <div x-cloak x-show="requiresManualConsignment">
                        <label class="block text-sm font-medium text-gray-700">Phiếu ký gửi</label>
                        <x-searchable-select
                            name="consignment_note_id"
                            :options="$consignmentOptions"
                            :selected="old('consignment_note_id', $product->consignment_note_id)"
                            placeholder="-- Chọn phiếu --"
                            search-placeholder="Tìm theo lần gửi hoặc ngày gửi"
                            empty-text="Không có phiếu phù hợp"
                            depends-on="supplier_id"
                            :dependency-value="$selectedSupplierId"
                        />
                        @error('consignment_note_id') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    <div x-cloak x-show="usesAutoGeneratedConsignment" class="rounded-2xl border border-dashed border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-700">
                        Phiếu ký gửi sẽ được tự sinh khi lưu sản phẩm cho loại nhà cung cấp này.
                        @if ($product->consignmentNote?->public_id)
                            Mã hiện tại: #{{ $product->consignmentNote->public_id_display }}.
                        @endif
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Danh mục</label>
                        <x-searchable-select
                            name="category_id"
                            :options="$categoryOptions"
                            :selected="old('category_id', $product->category_id)"
                            placeholder="-- Chọn danh mục --"
                            search-placeholder="Tìm theo mã hoặc tên"
                            empty-text="Không có danh mục phù hợp"
                        />
                        @error('category_id') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Tên sản phẩm</label>
                        <input name="name" value="{{ old('name', $product->name) }}" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900" required>
                        @error('name') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    <div class="grid gap-4 sm:grid-cols-2">
                        <div>
                            <label class="block text-sm font-medium text-gray-700">Giá bán</label>
                            <input type="number" step="0.01" name="sale_price" value="{{ old('sale_price', $product->sale_price) }}" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900" required>
                            @error('sale_price') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-gray-700">Số lượng</label>
                            <input type="number" min="1" name="quantity" value="{{ old('quantity', $product->quantity) }}" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900" required>
                            @error('quantity') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                        </div>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Ghi chú</label>
                        <textarea name="description" rows="5" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900">{{ old('description', $product->description) }}</textarea>
                        @error('description') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    <div class="flex items-center gap-3">
                        <button class="rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white">Cập nhật</button>
                        <a href="{{ route('products.index') }}" class="text-sm font-medium text-gray-600 hover:text-gray-900">Quay lại</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>
