<x-app-layout>
    <x-slot name="header">
        <div>
            <h2 class="text-2xl font-semibold text-gray-900">Sửa sản phẩm</h2>
            <p class="text-sm text-gray-500">Cập nhật thông tin sản phẩm, giá và ảnh chụp từ thiết bị.</p>
            <p class="mt-1 text-xs font-medium uppercase tracking-wide text-gray-400">Mã công khai: #{{ $product->public_id_display }}</p>
        </div>
    </x-slot>

    @php
        $supplierOptions = $suppliers->map(fn ($supplier) => [
            'value' => $supplier->id,
            'label' => '#'.$supplier->public_id_display.' - '.$supplier->name,
        ])->all();
        $supplierTypeMap = $suppliers->mapWithKeys(fn ($supplier) => [(string) $supplier->id => $supplier->type])->all();

        $categoryOptions = $categories->map(fn ($category) => [
            'value' => $category->id,
            'label' => '#'.$category->public_id_display.' - '.$category->name,
        ])->all();
    @endphp

    <div class="py-6 sm:py-10">
        <div class="mx-auto max-w-10xl px-3 sm:px-6 lg:px-10">
            <div
                class="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-gray-200 sm:p-6"
                x-data="{
                    supplierTypes: @js($supplierTypeMap),
                    manualTypes: @js(\App\Models\Supplier::MANUAL_CONSIGNMENT_TYPES),
                    autoTypes: @js(\App\Models\Supplier::AUTO_CONSIGNMENT_TYPES),
                    selectedSupplierId: @js((string) old('supplier_id', $product->supplier_id)),
                    init() {
                        window.addEventListener('searchable-select-change', (event) => {
                            if (event.detail?.name !== 'supplier_id') {
                                return;
                            }

                            this.selectedSupplierId = String(event.detail?.value ?? '');
                        });
                    },
                    get selectedSupplierType() {
                        return this.supplierTypes[this.selectedSupplierId] ?? '';
                    },
                    get requiresManualConsignment() {
                        return this.manualTypes.includes(this.selectedSupplierType);
                    },
                    get usesAutoGeneratedConsignment() {
                        return this.autoTypes.includes(this.selectedSupplierType);
                    },
                }"
            >
                @if ($product->isReturned())
                    <div class="mb-4 rounded-2xl bg-rose-50 px-4 py-3 text-sm text-rose-700 ring-1 ring-rose-200">
                        Sản phẩm này đã được trả cho người gửi từ {{ optional($product->returned_at)->format('d/m/Y H:i') }} và không thể bán trên hệ thống nữa.
                    </div>
                @endif

                <form method="POST" action="{{ route('products.update', $product) }}" enctype="multipart/form-data" class="space-y-4">
                    @csrf
                    @method('PUT')
                    <x-image-upload-preview
                        name="image"
                        label="Ảnh sản phẩm"
                        :current-url="$product->image_path ? asset('storage/' . $product->image_path) : null"
                        helper-text="Bạn có thể chụp ảnh hoặc chọn từ thư viện trên mọi thiết bị."
                    />
                    @error('image') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    @php
                        $selectedSupplierId = old('supplier_id', $product->supplier_id);
                    @endphp
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Nhà cung cấp</label>
                        <x-searchable-select
                            name="supplier_id"
                            :options="$supplierOptions"
                            :selected="$selectedSupplierId"
                            placeholder="-- Chọn NCC --"
                            search-placeholder="Tìm theo mã hoặc tên"
                            empty-text="Không có nhà cung cấp phù hợp"
                        />
                        @error('supplier_id') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    <div x-cloak x-show="requiresManualConsignment">
                        <label class="block text-sm font-medium text-gray-700">Phiếu ký gửi</label>
                        <x-searchable-select
                            name="consignment_note_id"
                            :options="$consignmentOptions"
                            :selected="old('consignment_note_id', $product->consignment_note_id)"
                            placeholder="-- Chọn phiếu --"
                            search-placeholder="Tìm theo lần gửi hoặc ngày gửi"
                            empty-text="Không có phiếu phù hợp"
                            depends-on="supplier_id"
                            :dependency-value="$selectedSupplierId"
                        />
                        @error('consignment_note_id') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    @if ($product->consignmentNote?->public_id)
                        <div x-cloak x-show="usesAutoGeneratedConsignment" class="rounded-2xl bg-slate-50 px-4 py-3 text-sm text-slate-700 ring-1 ring-slate-200">
                            Phiếu ký gửi hiện tại: <span class="font-semibold text-slate-900">#{{ $product->consignmentNote->public_id_display }}</span>
                        </div>
                    @endif
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Danh mục</label>
                        <x-searchable-select
                            name="category_id"
                            :options="$categoryOptions"
                            :selected="old('category_id', $product->category_id)"
                            placeholder="-- Chọn danh mục --"
                            search-placeholder="Tìm theo mã hoặc tên"
                            empty-text="Không có danh mục phù hợp"
                        />
                        @error('category_id') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Tên sản phẩm</label>
                        <input name="name" value="{{ old('name', $product->name) }}" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900" required>
                        @error('name') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    <div class="grid gap-4 sm:grid-cols-2">
                        <div>
                            <label class="block text-sm font-medium text-gray-700">Giá bán</label>
                            <input type="number" step="0.01" name="sale_price" value="{{ old('sale_price', $product->sale_price) }}" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900" required>
                            @error('sale_price') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-gray-700">Số lượng</label>
                            <input type="number" min="1" name="quantity" value="{{ old('quantity', $product->quantity) }}" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900" required>
                            @error('quantity') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                        </div>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Ghi chú</label>
                        <textarea name="description" rows="5" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900">{{ old('description', $product->description) }}</textarea>
                        @error('description') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                    </div>
                    <div class="flex flex-col gap-3 sm:flex-row sm:items-center">
                        <button class="rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white">Cập nhật</button>
                        <a href="{{ route('products.index') }}" class="text-sm font-medium text-gray-600 hover:text-gray-900">Quay lại</a>
                    </div>
                </form>
                @canany(['products.update', 'products.manage'])
                    @if (! $product->isReturned())
                        <div class="mt-6 border-t border-gray-200 pt-5">
                            <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                                <p class="text-sm text-gray-500">Đánh dấu sản phẩm đã trả cho người gửi để sản phẩm không còn bán được trên hệ thống.</p>
                                <x-confirm-action
                                    :name="'return-product-'.$product->public_id"
                                    :action="route('products.return', $product)"
                                    title="Trả sản phẩm cho người gửi"
                                    message="Sản phẩm #{{ $product->public_id_display }} - {{ $product->name }} sẽ được đánh dấu đã trả cho người gửi và không thể bán trên hệ thống nữa."
                                    confirm-text="Đánh dấu đã trả"
                                    trigger-text="Trả cho người gửi"
                                    method="POST"
                                    trigger-class="inline-flex items-center justify-center rounded-xl bg-rose-600 px-4 py-3 text-sm font-semibold text-white transition hover:bg-rose-500"
                                />
                            </div>
                        </div>
                    @endif
                @endcanany
                @can('products.delete')
                    <div class="mt-6 border-t border-gray-200 pt-5">
                        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                            <p class="text-sm text-gray-500">Thao tác này sẽ đưa sản phẩm vào thùng rác thay vì xóa hẳn.</p>
                            <x-confirm-action
                                :name="'delete-product-'.$product->public_id"
                                :action="route('products.destroy', $product)"
                                title="Đưa sản phẩm vào thùng rác"
                                message="Bạn có chắc chắn muốn đưa sản phẩm này vào thùng rác?"
                                confirm-text="Đưa vào thùng rác"
                                trigger-text="Đưa vào thùng rác"
                                trigger-class="inline-flex items-center justify-center rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700 hover:bg-red-100"
                            />
                        </div>
                    </div>
                @endcan
            </div>
        </div>
    </div>
</x-app-layout>
