<x-app-layout>
    <x-slot name="header">
        <div>
            <h2 class="text-2xl font-semibold text-gray-900">Sản phẩm</h2>
            <p class="text-sm text-gray-500">Thêm sản phẩm bằng file ảnh hoặc camera từ thiết bị di động.</p>
        </div>
    </x-slot>

    @php
        $supplierOptions = $suppliers->map(fn ($supplier) => [
            'value' => $supplier->id,
            'label' => '#'.$supplier->public_id_display.' - '.$supplier->name,
        ])->all();
        $supplierTypeMap = $suppliers->mapWithKeys(fn ($supplier) => [(string) $supplier->id => $supplier->type])->all();

        $categoryOptions = $categories->map(fn ($category) => [
            'value' => $category->id,
            'label' => '#'.$category->public_id_display.' - '.$category->name,
        ])->all();
    @endphp

    <div class="py-10">
        <div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
            @if (session('status'))
                <div class="rounded-2xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700 ring-1 ring-emerald-200">
                    {{ session('status') }}
                </div>
            @endif

                @if ($errors->any())
                    <div class="rounded-2xl bg-red-50 px-4 py-3 text-sm font-medium text-red-700 ring-1 ring-red-200">
                        <ul class="list-disc pl-5">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

            <div class="grid gap-6 lg:grid-cols-3">
                <div
                    class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-gray-200 lg:col-span-1"
                    x-data="{
                        supplierTypes: @js($supplierTypeMap),
                        manualTypes: @js(\App\Models\Supplier::MANUAL_CONSIGNMENT_TYPES),
                        autoTypes: @js(\App\Models\Supplier::AUTO_CONSIGNMENT_TYPES),
                        selectedSupplierId: @js((string) old('supplier_id')),
                        init() {
                            window.addEventListener('searchable-select-change', (event) => {
                                if (event.detail?.name !== 'supplier_id') {
                                    return;
                                }

                                this.selectedSupplierId = String(event.detail?.value ?? '');
                            });
                        },
                        get selectedSupplierType() {
                            return this.supplierTypes[this.selectedSupplierId] ?? '';
                        },
                        get requiresManualConsignment() {
                            return this.manualTypes.includes(this.selectedSupplierType);
                        },
                        get usesAutoGeneratedConsignment() {
                            return this.autoTypes.includes(this.selectedSupplierType);
                        },
                    }"
                >
                    @canany(['products.create', 'products.manage'])
                        <h3 class="text-lg font-semibold text-gray-900">Thêm sản phẩm</h3>
                        <form method="POST" action="{{ route('products.store') }}" enctype="multipart/form-data" class="mt-4 space-y-4">
                            @csrf
                            <x-image-upload-preview
                                name="image"
                                label="Ảnh sản phẩm"
                                helper-text="Kích thước tối đa 10MB. Định dạng chấp nhận: JPEG, PNG, WEBP. Trên điện thoại, trình duyệt có thể mở camera trực tiếp hoặc chọn ảnh từ bộ nhớ thiết bị."
                            />
                            @error('image') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                            <div>
                                <label class="block text-sm font-medium text-gray-700">Nhà cung cấp</label>
                                <x-searchable-select
                                    name="supplier_id"
                                    :options="$supplierOptions"
                                    :selected="old('supplier_id')"
                                    placeholder="-- Chọn NCC --"
                                    search-placeholder="Tìm theo mã hoặc tên"
                                    empty-text="Không có nhà cung cấp phù hợp"
                                />
                                @error('supplier_id') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                            </div>
                            <div x-cloak x-show="requiresManualConsignment">
                                <label class="block text-sm font-medium text-gray-700">Phiếu ký gửi</label>
                                <x-searchable-select
                                    name="consignment_note_id"
                                    :options="$consignmentOptions"
                                    :selected="old('consignment_note_id')"
                                    placeholder="-- Chọn phiếu --"
                                    search-placeholder="Tìm theo lần gửi hoặc ngày gửi"
                                    empty-text="Không có phiếu phù hợp"
                                    depends-on="supplier_id"
                                    :dependency-value="old('supplier_id')"
                                />
                                @error('consignment_note_id') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                            </div>
                            <div x-cloak x-show="usesAutoGeneratedConsignment" class="rounded-2xl border border-dashed border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-700">
                                Phiếu ký gửi sẽ được tự sinh khi lưu sản phẩm cho loại nhà cung cấp này.
                            </div>
                            <div>
                                <label class="block text-sm font-medium text-gray-700">Danh mục</label>
                                <x-searchable-select
                                    name="category_id"
                                    :options="$categoryOptions"
                                    :selected="old('category_id')"
                                    placeholder="-- Chọn danh mục --"
                                    search-placeholder="Tìm theo mã hoặc tên"
                                    empty-text="Không có danh mục phù hợp"
                                />
                                @error('category_id') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                            </div>
                            <div>
                                <label class="block text-sm font-medium text-gray-700">Tên sản phẩm</label>
                                <input name="name" value="{{ old('name') }}" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900" required>
                                @error('name') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                            </div>
                            <div class="grid gap-4 sm:grid-cols-2">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700">Giá bán</label>
                                    <input type="number" step="0.01" name="sale_price" value="{{ old('sale_price', 0) }}" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900" required>
                                    @error('sale_price') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                                </div>
                                <div>
                                    <label class="block text-sm font-medium text-gray-700">Số lượng</label>
                                    <input type="number" min="1" name="quantity" value="{{ old('quantity', 1) }}" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900" required>
                                    @error('quantity') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                                </div>
                            </div>
                            <div>
                                <label class="block text-sm font-medium text-gray-700">Ghi chú</label>
                                <textarea name="description" rows="4" class="mt-1 w-full rounded-xl border-gray-300 focus:border-slate-900 focus:ring-slate-900">{{ old('description') }}</textarea>
                                @error('description') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror
                            </div>
                            <button class="w-full rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white transition hover:bg-slate-800">Lưu sản phẩm</button>
                        </form>
                    @else
                        <h3 class="text-lg font-semibold text-gray-900">Thêm sản phẩm</h3>
                        <p class="mt-3 text-sm text-gray-500">Bạn chỉ có quyền xem sản phẩm.</p>
                    @endcanany
                </div>

                <div
                    class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-gray-200 lg:col-span-2"
                    x-data="{
                        imageZoomOpen: false,
                        imageZoomSrc: '',
                        imageZoomAlt: '',
                        openImageZoom(src, alt) {
                            this.imageZoomSrc = src;
                            this.imageZoomAlt = alt;
                            this.imageZoomOpen = true;
                        },
                        closeImageZoom() {
                            this.imageZoomOpen = false;
                        },
                    }"
                >
                    <div class="flex flex-wrap items-center justify-between gap-3">
                        <h3 class="text-lg font-semibold text-gray-900">Danh sách</h3>
                        <form method="GET" action="{{ route('products.index') }}" class="flex flex-wrap items-center gap-2">
                            <x-per-page-select :value="request('per_page', 10)" />
                            <input name="public_id" value="{{ request('public_id') }}" class="w-64 rounded-xl border-gray-300 text-sm focus:border-slate-900 focus:ring-slate-900" placeholder="Tìm bằng mã công khai">
                            <button class="rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white">Tìm</button>
                        </form>
                    </div>
                    <div class="mt-4 overflow-x-auto">
                        <table class="min-w-full divide-y divide-gray-200 text-sm">
                            <thead class="text-left text-xs uppercase tracking-wide text-gray-500">
                                <tr>
                                    <th class="py-3 pr-4">Mã hàng</th>
                                    <th class="py-3 pr-4">Mã NCC</th>
                                    <th class="py-3 pr-4">Ảnh</th>
                                    <th class="py-3 pr-4">Tên sản phẩm</th>
                                    <th class="py-3 pr-4">Giá</th>
                                    <th class="py-3 pr-4">Tồn kho</th>
                                    <th class="py-3 pr-4">Lần gửi</th>
                                    <th class="py-3 pr-4">Danh mục</th>
                                    <th class="py-3 pr-4 text-right">Thao tác</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-100">
                                @forelse ($products as $product)
                                    <tr>
                                        <td class="py-3 pr-4 font-medium text-slate-900">#{{ $product->public_id_display }}</td>
                                        <td class="py-3 pr-4 text-gray-600">
                                            <div class="font-medium text-gray-900">{{ $product->supplier?->public_id ? '#'.$product->supplier->public_id_display : '---' }}</div>
                                            <div class="text-xs text-gray-500">{{ $product->supplier?->name ?? '---' }}</div>
                                        </td>
                                        <td class="py-3 pr-4">
                                            @if ($product->image_path)
                                                <button
                                                    type="button"
                                                    class="group block"
                                                    @click="openImageZoom(@js(asset('storage/' . $product->image_path)), @js($product->name))"
                                                >
                                                    <img src="{{ asset('storage/' . $product->image_path) }}" alt="{{ $product->name }}" class="h-14 w-14 rounded-xl object-cover ring-1 ring-gray-200 transition group-hover:scale-105 group-hover:ring-slate-400">
                                                </button>
                                            @else
                                                <div class="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-100 text-xs font-semibold text-slate-500 ring-1 ring-gray-200">Không ảnh</div>
                                            @endif
                                        </td>
                                        <td class="py-3 pr-4 font-medium text-gray-900">{{ $product->name }}</td>
                                        <td class="py-3 pr-4 text-gray-600">{{ number_format($product->sale_price ?? 0, 0, ',', '.') }} đ</td>
                                        <td class="py-3 pr-4 text-gray-600">{{ $product->quantity }}</td>
                                        <td class="py-3 pr-4 text-gray-600">
                                            <div class="font-medium text-gray-900">Lần {{ $product->send_round ?? 1 }}</div>
                                            <div class="text-xs text-gray-500">{{ $product->send_summary ?? '---' }}</div>
                                        </td>
                                        <td class="py-3 pr-4 text-gray-600">
                                            <div class="font-medium text-gray-900">{{ $product->category?->public_id ? '#'.$product->category->public_id_display : '---' }}</div>
                                            <div class="text-xs text-gray-500">{{ $product->category?->name ?? '---' }}</div>
                                        </td>
                                        <td class="py-3 pr-4 text-right whitespace-nowrap">
                                            @can('products.view')
                                                <a href="{{ route('products.label', $product) }}" target="_blank" rel="noopener" class="text-slate-900 hover:underline">In mã hàng</a>
                                            @endcan
                                            @canany(['products.update', 'products.manage'])
                                                <a href="{{ route('products.edit', $product) }}" class="ms-4 text-slate-900 hover:underline">Sửa</a>
                                            @endcanany
                                            @can('products.delete')
                                                <span class="ms-4 inline-block align-middle">
                                                    <x-confirm-action
                                                        :name="'delete-product-'.$product->public_id"
                                                        :action="route('products.destroy', $product)"
                                                        title="Xoá sản phẩm"
                                                        message="Bạn có chắc chắn muốn xoá sản phẩm này?"
                                                        confirm-text="Xoá"
                                                        trigger-text="Xoá"
                                                    />
                                                </span>
                                            @endcan
                                        </td>
                                    </tr>
                                @empty
                                    <tr><td colspan="9" class="py-8 text-center text-gray-500">Chưa có sản phẩm nào.</td></tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    <div class="mt-4">{{ $products->links() }}</div>

                    <div
                        x-cloak
                        x-show="imageZoomOpen"
                        x-transition.opacity
                        class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4"
                        @click.self="closeImageZoom()"
                        @keydown.escape.window="closeImageZoom()"
                    >
                        <div class="relative w-full max-w-5xl overflow-hidden rounded-3xl bg-white shadow-2xl">
                            <button type="button" class="absolute right-3 top-3 z-10 rounded-full bg-white/90 px-3 py-2 text-sm font-semibold text-slate-700 shadow-sm ring-1 ring-slate-200 hover:bg-white" @click="closeImageZoom()">Đóng</button>
                            <img :src="imageZoomSrc" :alt="imageZoomAlt" class="max-h-[85vh] w-full bg-slate-950 object-contain">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
