<?php

namespace App\Models;

use App\Models\Concerns\HasPublicId;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ConsignmentNote extends Model
{
    use HasFactory;
    use HasPublicId;

    public const AUTO_GENERATED_NOTE_MARKER = 'AUTO_GENERATED_FROM_PRODUCT';

    protected $fillable = [
        'public_id',
        'responsible_user_id',
        'responsible_name',
        'supplier_id',
        'sent_date',
        'quantity',
        'notes',
    ];

    protected $casts = [
        'sent_date' => 'date',
        'quantity' => 'integer',
    ];

    public function responsibleUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'responsible_user_id');
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Supplier::class);
    }

    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }

    public function isAutoGenerated(): bool
    {
        return $this->notes === self::AUTO_GENERATED_NOTE_MARKER;
    }
}
