<?php

namespace App\Models;

use App\Models\Concerns\HasPublicId;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Supplier extends Model
{
    use HasFactory;
    use HasPublicId;

    public const MANUAL_CONSIGNMENT_TYPES = [
        'ncc_it_san_pham',
        'ncc_nhieu_san_pham',
    ];

    public const AUTO_CONSIGNMENT_TYPES = [
        'cho_tang',
        'khach_si',
        'hang_thu_mua',
    ];

    public const TYPES = [
        'cho_tang' => 'Cho tặng',
        'khach_si' => 'Khách sỉ',
        'ncc_it_san_pham' => 'NCC ít sản phẩm',
        'ncc_nhieu_san_pham' => 'NCC nhiều sản phẩm',
        'hang_thu_mua' => 'Hàng thu mua',
    ];

    protected $fillable = [
        'public_id',
        'responsible_name',
        'type',
        'name',
        'phone',
        'bank_name',
        'bank_account_name',
        'bank_account_number',
        'notes',
    ];

    public function consignmentNotes(): HasMany
    {
        return $this->hasMany(ConsignmentNote::class);
    }

    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }

    public static function typeRequiresManualConsignment(?string $type): bool
    {
        return in_array($type, self::MANUAL_CONSIGNMENT_TYPES, true);
    }

    public static function typeUsesAutoGeneratedConsignment(?string $type): bool
    {
        return in_array($type, self::AUTO_CONSIGNMENT_TYPES, true);
    }

    public function requiresManualConsignment(): bool
    {
        return self::typeRequiresManualConsignment($this->type);
    }

    public function usesAutoGeneratedConsignment(): bool
    {
        return self::typeUsesAutoGeneratedConsignment($this->type);
    }
}
